### ISSUE TITLE
Error during install : ModuleNotFoundError: No module named 'markdown'

### ISSUE THREAD

**Issue by sebma** [menduo/mdtree#2]
Hi,

I get this when running `pip install mdtree` on both Linux and MacOS : 
```python
Collecting mdtree
  Downloading https://files.pythonhosted.org/packages/c6/ca/5af23d8d4a0634b9bba0b7469be15c01d57850c20542e2a884a4a91d18c6/mdtree-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-buxnaxyp/mdtree/setup.py", line 4, in <module>
        import mdtree
      File "/tmp/pip-install-buxnaxyp/mdtree/mdtree/__init__.py", line 5, in <module>
        from mdtree.main import MdTree, convert_from_file
      File "/tmp/pip-install-buxnaxyp/mdtree/mdtree/main.py", line 7, in <module>
        import markdown
    ModuleNotFoundError: No module named 'markdown'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-buxnaxyp/mdtree/
```

Can you help me ?

**Comment by menduo** [comment]
Sorry, that's a bug. Please install again:

```bash
$ pip install mdtree==0.6 --index-url https://pypi.org/simple
```

**Comment by sebma** [comment]
It worked thanks

**Comment by menduo** [comment]
@sebma You are welcome.
